export const GET_ACCOUNT_AUDIT_LOGS_REQUEST = 'GET_ACCOUNT_AUDIT_LOGS_REQUEST';
export const GET_ACCOUNT_AUDIT_LOGS_SUCCESS = 'GET_ACCOUNT_AUDIT_LOGS_SUCCESS';
export const GET_ACCOUNT_AUDIT_LOGS_FAIL = 'GET_ACCOUNT_AUDIT_LOGS_FAIL'; 