export const GET_TRUCK_AUDIT_LOGS_REQUEST = 'GET_TRUCK_AUDIT_LOGS_REQUEST';
export const GET_TRUCK_AUDIT_LOGS_SUCCESS = 'GET_TRUCK_AUDIT_LOGS_SUCCESS';
export const GET_TRUCK_AUDIT_LOGS_FAIL = 'GET_TRUCK_AUDIT_LOGS_FAIL'; 