export const GET_VESSEL_AUDIT_LOGS_REQUEST = 'GET_VESSEL_AUDIT_LOGS_REQUEST';
export const GET_VESSEL_AUDIT_LOGS_SUCCESS = 'GET_VESSEL_AUDIT_LOGS_SUCCESS';
export const GET_VESSEL_AUDIT_LOGS_FAIL = 'GET_VESSEL_AUDIT_LOGS_FAIL'; 